# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(1440, 806)
        Main.setMinimumSize(QtCore.QSize(0, 0))
        Main.setMaximumSize(QtCore.QSize(3000, 1000))
        Main.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.centralwidget = QtWidgets.QWidget(Main)
        self.centralwidget.setMinimumSize(QtCore.QSize(1440, 700))
        self.centralwidget.setMaximumSize(QtCore.QSize(1440, 16777215))
        self.centralwidget.setStyleSheet("background-color: #fff")
        self.centralwidget.setObjectName("centralwidget")
        self.main_frame = QtWidgets.QFrame(self.centralwidget)
        self.main_frame.setGeometry(QtCore.QRect(0, 70, 1281, 691))
        self.main_frame.setStyleSheet("background-color: #FAFAFA;\n"
"border: 1px solid #C4C4C4;\n"
"box-sizing: border-box;\n"
"border-radius: 16px;")
        self.main_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.main_frame.setObjectName("main_frame")
        self.tools = QtWidgets.QFrame(self.main_frame)
        self.tools.setGeometry(QtCore.QRect(20, 210, 680, 371))
        self.tools.setStyleSheet("QFrame\n"
"{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 0;\n"
"}\n"
"\n"
"QLabel \n"
"{\n"
"    font-family: \'Inter\';\n"
"    font-weight: 700;\n"
"    font-size: 32px;\n"
"    color: #000000;\n"
"    border: 0;\n"
"    text-align: left;\n"
"}")
        self.tools.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.tools.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.tools.setObjectName("tools")
        self.tools_title = QtWidgets.QLabel(self.tools)
        self.tools_title.setGeometry(QtCore.QRect(20, 10, 241, 40))
        self.tools_title.setObjectName("tools_title")
        self.export_min_title = QtWidgets.QLabel(self.tools)
        self.export_min_title.setGeometry(QtCore.QRect(20, 260, 101, 30))
        self.export_min_title.setStyleSheet("QLabel \n"
"{\n"
"    font-family: \'Inter\';\n"
"    font-weight: 400;\n"
"    font-size: 24px;\n"
"    color: #000000;\n"
"    border: 0;\n"
"    text-align: left;\n"
"}")
        self.export_min_title.setObjectName("export_min_title")
        self.btn_export_hex = QtWidgets.QPushButton(self.tools)
        self.btn_export_hex.setGeometry(QtCore.QRect(220, 300, 180, 50))
        self.btn_export_hex.setStyleSheet("QPushButton\n"
"{\n"
"    font-family: \'Inter\';\n"
"    font-weight: 400;\n"
"    font-size: 18px;\n"
"    color: #79C9CA;\n"
"    background-color: rgba(121, 201, 202, 0.1);\n"
"    border: 1px solid #C4C4C4;\n"
"    border-radius: 16px;\n"
"    padding: 0 15px 0 15px;\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    background-color: rgba(121, 201, 202, 0.2);\n"
"    border: 1px solid #C4C4C4;\n"
"}\n"
"\n"
"QPushButton::pressed\n"
"{\n"
"    background-color: rgba(121, 201, 202, 0.3);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("101.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_export_hex.setIcon(icon)
        self.btn_export_hex.setIconSize(QtCore.QSize(50, 50))
        self.btn_export_hex.setObjectName("btn_export_hex")
        self.btn_export_bin = QtWidgets.QPushButton(self.tools)
        self.btn_export_bin.setGeometry(QtCore.QRect(20, 300, 180, 50))
        self.btn_export_bin.setStyleSheet("QPushButton\n"
"{\n"
"    font-family: \'Inter\';\n"
"    font-weight: 400;\n"
"    font-size: 18px;\n"
"    color: #77A4D3;\n"
"    background-color: rgba(119, 164, 211, 0.1);\n"
"    border: 1px solid #C4C4C4;\n"
"    border-radius: 16px;\n"
"    padding: 0 15px 0 15px;\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    background-color: rgba(119, 164, 211, 0.2);\n"
"    border: 1px solid #C4C4C4;\n"
"}\n"
"\n"
"QPushButton::pressed\n"
"{\n"
"    background-color: rgba(119, 164, 211, 0.3);\n"
"}")
        self.btn_export_bin.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("0x0.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_export_bin.setIcon(icon1)
        self.btn_export_bin.setIconSize(QtCore.QSize(50, 50))
        self.btn_export_bin.setObjectName("btn_export_bin")
        self.btn_merge = QtWidgets.QToolButton(self.tools)
        self.btn_merge.setGeometry(QtCore.QRect(510, 100, 150, 150))
        self.btn_merge.setToolTip("")
        self.btn_merge.setStatusTip("")
        self.btn_merge.setAccessibleName("")
        self.btn_merge.setStyleSheet("QToolButton\n"
"{\n"
"    padding: 0;\n"
"    font-family: \'Inter\';\n"
"    font-weight: 400;\n"
"    font-size: 20px;\n"
"    color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(119, 164, 211, 255), stop:1 rgba(121, 201, 202, 255));\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(119, 164, 211, 35), stop:1 rgba(121, 201, 202, 35));\n"
"    border: 1px solid #C4C4C4;\n"
"    border-radius: 16px;\n"
"}\n"
"\n"
"QToolButton::hover\n"
"{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(119, 164, 211, 50), stop:1 rgba(121, 201, 202, 50));\n"
"    border: 1px solid #C4C4C4;\n"
"}\n"
"\n"
"QToolButton::pressed\n"
"{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(119, 164, 211, 70), stop:1 rgba(121, 201, 202, 70));\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("merge.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_merge.setIcon(icon2)
        self.btn_merge.setIconSize(QtCore.QSize(100, 100))
        self.btn_merge.setCheckable(False)
        self.btn_merge.setChecked(False)
        self.btn_merge.setAutoRepeat(False)
        self.btn_merge.setAutoExclusive(False)
        self.btn_merge.setAutoRepeatInterval(100)
        self.btn_merge.setPopupMode(QtWidgets.QToolButton.ToolButtonPopupMode.DelayedPopup)
        self.btn_merge.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.btn_merge.setObjectName("btn_merge")
        self.export_min_title_2 = QtWidgets.QLabel(self.tools)
        self.export_min_title_2.setGeometry(QtCore.QRect(420, 260, 141, 30))
        self.export_min_title_2.setStyleSheet("QLabel \n"
"{\n"
"    font-family: \'Inter\';\n"
"    font-weight: 400;\n"
"    font-size: 24px;\n"
"    color: #000000;\n"
"    border: 0;\n"
"    text-align: left;\n"
"}")
        self.export_min_title_2.setObjectName("export_min_title_2")
        self.btn_export_hex_5 = QtWidgets.QPushButton(self.tools)
        self.btn_export_hex_5.setGeometry(QtCore.QRect(420, 300, 240, 51))
        self.btn_export_hex_5.setStyleSheet("QPushButton\n"
"{\n"
"    font-family: \'Inter\';\n"
"    font-weight: 400;\n"
"    font-size: 18px;\n"
"    background-color: #fff;\n"
"    border: 1px solid #C4C4C4;\n"
"    border-radius: 16px;\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    background-color: rgba(196, 196, 196, 0.125);\n"
"}\n"
"\n"
"QPushButton::pressed\n"
"{\n"
"    background-color: rgba(196, 196, 196, 0.25);\n"
"}")
        self.btn_export_hex_5.setIconSize(QtCore.QSize(50, 50))
        self.btn_export_hex_5.setObjectName("btn_export_hex_5")
        self.listView = QtWidgets.QListView(self.tools)
        self.listView.setGeometry(QtCore.QRect(20, 100, 471, 151))
        self.listView.setStyleSheet("QListView {\n"
"    border: 1px solid #C4C4C4;\n"
"    border-radius: 16px;\n"
"}")
        self.listView.setObjectName("listView")
        self.export_min_title_3 = QtWidgets.QLabel(self.tools)
        self.export_min_title_3.setGeometry(QtCore.QRect(20, 60, 261, 25))
        self.export_min_title_3.setStyleSheet("QLabel \n"
"{\n"
"    font-family: \'Inter\';\n"
"    font-weight: 400;\n"
"    font-size: 24px;\n"
"    color: #000000;\n"
"    border: 0;\n"
"    text-align: left;\n"
"}")
        self.export_min_title_3.setObjectName("export_min_title_3")
        self.checkBox = QtWidgets.QCheckBox(self.tools)
        self.checkBox.setGeometry(QtCore.QRect(430, 70, 20, 20))
        self.checkBox.setMouseTracking(True)
        self.checkBox.setStyleSheet("QCheckBox {\n"
"    border: 1px solid #C4C4C4;\n"
"    border-radius: 16px;\n"
"}")
        self.checkBox.setText("")
        self.checkBox.setIconSize(QtCore.QSize(25, 25))
        self.checkBox.setCheckable(True)
        self.checkBox.setTristate(False)
        self.checkBox.setObjectName("checkBox")
        self.files = QtWidgets.QFrame(self.main_frame)
        self.files.setGeometry(QtCore.QRect(20, 20, 680, 191))
        self.files.setStyleSheet("QFrame \n"
"{\n"
"    border: 0;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0));\n"
"}\n"
"\n"
"QLabel \n"
"{\n"
"    font-family: \'Inter\';\n"
"    font-weight: 700;\n"
"    font-size: 32px;\n"
"    color: #000000;\n"
"    border: 0;\n"
"    text-align: left;\n"
"}\n"
"\n"
"QToolButton\n"
"{\n"
"    padding: 10 0 -5 0;\n"
"    font-family: \'Inter\';\n"
"    font-weight: 400;\n"
"    font-size: 16px;\n"
"    position: top;\n"
"    background-color: #FFFFFF;\n"
"    border: 1px dashed #C4C4C4;\n"
"    border-radius: 16px;\n"
"}\n"
"\n"
"QToolButton::hover\n"
"{\n"
"    background-color: rgba(196, 196, 196, 0.125);\n"
"    border: 1px solid #C4C4C4;\n"
"}\n"
"\n"
"QToolButton::pressed\n"
"{\n"
"    background-color: rgba(196, 196, 196, 0.25);\n"
"    border: 1px solid #C4C4C4;\n"
"}\n"
"")
        self.files.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.files.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.files.setObjectName("files")
        self.files_title = QtWidgets.QLabel(self.files)
        self.files_title.setGeometry(QtCore.QRect(0, 0, 130, 30))
        self.files_title.setAutoFillBackground(False)
        self.files_title.setStyleSheet("")
        self.files_title.setObjectName("files_title")
        self.btn_files_1 = QtWidgets.QToolButton(self.files)
        self.btn_files_1.setGeometry(QtCore.QRect(0, 50, 120, 120))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("file_off.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_files_1.setIcon(icon3)
        self.btn_files_1.setIconSize(QtCore.QSize(60, 60))
        self.btn_files_1.setCheckable(False)
        self.btn_files_1.setChecked(False)
        self.btn_files_1.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.btn_files_1.setObjectName("btn_files_1")
        self.btn_files_2 = QtWidgets.QToolButton(self.files)
        self.btn_files_2.setGeometry(QtCore.QRect(140, 50, 120, 120))
        self.btn_files_2.setIcon(icon3)
        self.btn_files_2.setIconSize(QtCore.QSize(60, 60))
        self.btn_files_2.setCheckable(False)
        self.btn_files_2.setChecked(False)
        self.btn_files_2.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.btn_files_2.setObjectName("btn_files_2")
        self.btn_files_3 = QtWidgets.QToolButton(self.files)
        self.btn_files_3.setEnabled(True)
        self.btn_files_3.setGeometry(QtCore.QRect(280, 50, 120, 120))
        self.btn_files_3.setIcon(icon3)
        self.btn_files_3.setIconSize(QtCore.QSize(60, 60))
        self.btn_files_3.setCheckable(False)
        self.btn_files_3.setChecked(False)
        self.btn_files_3.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.btn_files_3.setObjectName("btn_files_3")
        self.btn_files_4 = QtWidgets.QToolButton(self.files)
        self.btn_files_4.setGeometry(QtCore.QRect(420, 50, 120, 120))
        self.btn_files_4.setIcon(icon3)
        self.btn_files_4.setIconSize(QtCore.QSize(60, 60))
        self.btn_files_4.setCheckable(False)
        self.btn_files_4.setChecked(False)
        self.btn_files_4.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.btn_files_4.setObjectName("btn_files_4")
        self.btn_files_5 = QtWidgets.QToolButton(self.files)
        self.btn_files_5.setGeometry(QtCore.QRect(560, 50, 120, 120))
        self.btn_files_5.setIcon(icon3)
        self.btn_files_5.setIconSize(QtCore.QSize(60, 60))
        self.btn_files_5.setCheckable(False)
        self.btn_files_5.setChecked(False)
        self.btn_files_5.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.btn_files_5.setObjectName("btn_files_5")
        self.editor = QtWidgets.QFrame(self.main_frame)
        self.editor.setGeometry(QtCore.QRect(720, 20, 531, 481))
        self.editor.setStyleSheet("QFrame\n"
"{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 0;\n"
"}\n"
"\n"
"QLabel \n"
"{\n"
"    font-family: \'Inter\';\n"
"    font-weight: 700;\n"
"    font-size: 32px;\n"
"    color: #000000;\n"
"    border: 0;\n"
"    text-align: left;\n"
"}")
        self.editor.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.editor.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.editor.setObjectName("editor")
        self.tools_title_2 = QtWidgets.QLabel(self.editor)
        self.tools_title_2.setGeometry(QtCore.QRect(20, 10, 241, 40))
        self.tools_title_2.setObjectName("tools_title_2")
        self.btn_export_hex_2 = QtWidgets.QPushButton(self.editor)
        self.btn_export_hex_2.setGeometry(QtCore.QRect(20, 70, 180, 51))
        self.btn_export_hex_2.setStyleSheet("QPushButton\n"
"{\n"
"    font-family: \'Inter\';\n"
"    font-weight: 400;\n"
"    font-size: 18px;\n"
"    background-color: #fff;\n"
"    border: 1px solid #C4C4C4;\n"
"    border-radius: 16px;\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    background-color: rgba(121, 201, 202, 0.2);\n"
"    border: 1px solid #C4C4C4;\n"
"}\n"
"\n"
"QPushButton::pressed\n"
"{\n"
"    background-color: rgba(121, 201, 202, 0.3);\n"
"}")
        self.btn_export_hex_2.setIconSize(QtCore.QSize(50, 50))
        self.btn_export_hex_2.setObjectName("btn_export_hex_2")
        self.btn_export_hex_3 = QtWidgets.QPushButton(self.editor)
        self.btn_export_hex_3.setGeometry(QtCore.QRect(220, 70, 180, 51))
        self.btn_export_hex_3.setStyleSheet("QPushButton\n"
"{\n"
"    font-family: \'Inter\';\n"
"    font-weight: 400;\n"
"    font-size: 18px;\n"
"    background-color: #fff;\n"
"    border: 1px solid #C4C4C4;\n"
"    border-radius: 16px;\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    color: rgb(229, 46, 46);\n"
"    background-color: ;\n"
"    background-color: rgba(229, 46, 46, 0.1);\n"
"    border: 1px solid #C4C4C4;\n"
"}\n"
"\n"
"QPushButton::pressed\n"
"{\n"
"    color: rgb(229, 46, 46);\n"
"    background-color: rgba(229, 46, 46, 0.15);\n"
"}")
        self.btn_export_hex_3.setIconSize(QtCore.QSize(50, 50))
        self.btn_export_hex_3.setObjectName("btn_export_hex_3")
        self.frame = QtWidgets.QFrame(self.editor)
        self.frame.setGeometry(QtCore.QRect(30, 180, 421, 271))
        self.frame.setStyleSheet("QFrame {\n"
"    background-color: #FAFAFA;\n"
"    border: 0;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.textEdit = QtWidgets.QTextEdit(self.frame)
        self.textEdit.setGeometry(QtCore.QRect(0, 0, 111, 271))
        self.textEdit.setStyleSheet("QTextEdit {\n"
"    font-family: \'JetBrains Mono\';\n"
"    font-weight: 400;\n"
"    font-size: 18px;\n"
"    color: #009C93;\n"
"\n"
"    border: 1px solid #C4C4C4;\n"
"    border-radius: 16px;\n"
"    background-color: rgba(0, 156, 147, 0.1);\n"
"\n"
"    padding: 5px;\n"
"}")
        self.textEdit.setObjectName("textEdit")
        self.mes = QtWidgets.QFrame(self.main_frame)
        self.mes.setGeometry(QtCore.QRect(20, 600, 680, 51))
        self.mes.setStyleSheet("QFrame\n"
"{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 0;\n"
"}")
        self.mes.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.mes.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.mes.setObjectName("mes")
        self.name_prj = QtWidgets.QLabel(self.centralwidget)
        self.name_prj.setGeometry(QtCore.QRect(20, 10, 1031, 45))
        self.name_prj.setStyleSheet("font-family: \'Inter\';\n"
"font-style: normal;\n"
"font-weight: 700;\n"
"font-size: 40px;\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(7, 119, 164, 206));")
        self.name_prj.setObjectName("name_prj")
        Main.setCentralWidget(self.centralwidget)

        self.retranslateUi(Main)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "HEX files tools"))
        self.tools_title.setText(_translate("Main", "Инструменты"))
        self.export_min_title.setText(_translate("Main", "Экспорт"))
        self.btn_export_hex.setText(_translate("Main", "        в bin"))
        self.btn_export_bin.setText(_translate("Main", "        в hex"))
        self.btn_merge.setText(_translate("Main", "Объединить"))
        self.export_min_title_2.setText(_translate("Main", "Добавить"))
        self.btn_export_hex_5.setText(_translate("Main", "Добавить"))
        self.export_min_title_3.setText(_translate("Main", "Регионы hex-файлов"))
        self.files_title.setText(_translate("Main", "Файлы"))
        self.btn_files_1.setText(_translate("Main", "Добавить"))
        self.btn_files_2.setText(_translate("Main", "Добавить"))
        self.btn_files_3.setText(_translate("Main", "Добавить"))
        self.btn_files_4.setText(_translate("Main", "Добавить"))
        self.btn_files_5.setText(_translate("Main", "Добавить"))
        self.tools_title_2.setText(_translate("Main", "Редактор"))
        self.btn_export_hex_2.setText(_translate("Main", "Сохранить"))
        self.btn_export_hex_3.setText(_translate("Main", "Удалить"))
        self.name_prj.setText(_translate("Main", "Инструментарий для работы с HEX-файлами"))
